# Generated by Django 5.2.1 on 2025-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_uploadedimage_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
