# Generated by Django 5.2.1 on 2025-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_uploadedimage_delete_imageindb'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
