# Generated by Django 5.2.1 on 2025-05-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_uploadedimage_delete_image_delete_post'),
    ]

    operations = [
    ]
